# Generated by Django 4.0.6 on 2022-08-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_caseaward_respondent_claiment_casedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('claiment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('claiment_adv_name', models.CharField(blank=True, max_length=200, null=True)),
                ('claiment_number', models.CharField(blank=True, max_length=10, null=True)),
                ('claiment_email', models.EmailField(max_length=254)),
                ('claiment_address', models.CharField(blank=True, max_length=200, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('respondent_adv_name', models.CharField(blank=True, max_length=200, null=True)),
                ('respondent_number', models.CharField(blank=True, max_length=10, null=True)),
                ('respondent_email', models.EmailField(max_length=254)),
                ('respondent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.caseaward')),
            ],
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='case',
        ),
        migrations.DeleteModel(
            name='Claiment',
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
