# Generated by Django 4.0.6 on 2022-08-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clientdetail_remove_respondent_case_delete_claiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casedetail',
            old_name='case',
            new_name='cases',
        ),
        migrations.RenameField(
            model_name='clientdetail',
            old_name='case',
            new_name='cases',
        ),
    ]
