# Generated by Django 4.0.6 on 2022-08-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_case_casedetail_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetail',
            name='file',
        ),
        migrations.RemoveField(
            model_name='casedetail',
            name='notification',
        ),
    ]
