# Generated by Django 4.0.6 on 2022-08-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_remove_casedetail_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesDetail',
            fields=[
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('disputeValue', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('claimantName', models.CharField(blank=True, max_length=200, null=True)),
                ('claimantNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('claimantEmail', models.EmailField(max_length=254)),
                ('claimant_address', models.CharField(blank=True, max_length=200, null=True)),
                ('respondentName', models.CharField(blank=True, max_length=200, null=True)),
                ('respondentNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('respondentEmail', models.EmailField(max_length=254)),
                ('respondentAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientdetail',
            name='cases',
        ),
        migrations.RenameModel(
            old_name='CaseAward',
            new_name='Cases',
        ),
        migrations.DeleteModel(
            name='CaseDetail',
        ),
        migrations.DeleteModel(
            name='ClientDetail',
        ),
        migrations.AddField(
            model_name='client',
            name='cases',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cases'),
        ),
        migrations.AddField(
            model_name='casesdetail',
            name='cases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cases'),
        ),
    ]
