# Generated by Django 4.0.6 on 2022-08-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_casesdetail_client_remove_clientdetail_cases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='claimant_address',
            new_name='claimantAddress',
        ),
    ]
